---
- name: check installed plugins' version
  shell: >
    cat {{ roundcube_www_dir }}/plugins/{{ item.name }}/.version || echo ''
  changed_when: false
  register: _installed_versions
  with_items: roundcube_plugins | selectattr('url', 'defined') | list

- name: download and extract external plugins in tar.gz
  shell: >
    mkdir -p {{ item.0.name }}
    && curl -L {{ item.0.url }} | tar -xz -C {{ item.0.name }} --strip-components=1
    && echo -n "{{ item.0.version }}" > {{ item.0.name }}/.version
    chdir={{ roundcube_www_dir }}/plugins
  when: item.0.version != item.1.stdout
  with_together:
    - roundcube_plugins | selectattr('url', 'defined') | list
    - _installed_versions.results | default([])
