---
- name: list installed PHP modules
  shell: >
    php-fpm -m | grep -Po '^[\w- ]+\w$'
  register: php_modules
  changed_when: false
  tags: check

- name: check if required PHP modules are compiled
  fail: >
    msg="Missing required PHP modules:
    {{ roundcube_php_modules | difference(php_modules.stdout_lines) | join(', ') }}"
  when: roundcube_php_modules | difference(php_modules.stdout_lines)
  tags: check

- name: prepare directories
  file: >
    state=directory
    path={{ item.path }}
    owner={{ item.owner | default(roundcube_user) }}
    group={{ item.group | default(roundcube_group) }}
    mode={{ item.mode | default('0755') }}
  with_items:
    - { path: "{{ roundcube_base_dir }}", owner: root, group: root }
    - { path: "{{ roundcube_www_dir }}",  owner: root, group: root }
    - { path: "{{ roundcube_conf_dir }}", owner: root, group: root }
    - { path: "{{ roundcube_conf_dir }}/plugins", owner: root, group: root }
    - { path: "{{ roundcube_temp_dir }}", mode: '0750' }
    - { path: "{{ roundcube_logs_dir }}" }

- name: "symlink chrooted /log to /var/log/{{ roundcube_name }}"
  file: >
    state=link
    src={{ roundcube_logs_dir }}
    dest=/var/log/{{roundcube_name }}
  when: roundcube_chroot_enabled
